--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NopeNotDark/CPE
build-by-default: true
branches:
- master
projects:
  CPE:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^3.1.0
    lints:
      phpstan: false
...
